### ISSUE TITLE
Demo link?

### ISSUE THREAD

**Issue by lostpupil** [nandoflorestan/mithril-widgets#1]
Hey there.
I am make mithril-widgets too, instead I am using bulma [Link](https://github.com/lostpupil/mithril-widgets).
I am wondering is there any demo link or detailed description?

**Comment by nandoflorestan** [comment]
Hello lostpupil!

I like your project and your coding style, congratulations.  You are welcome to our code, of course.  Unfortunately it seems that @pitymaia and I have neglected the creation of a demo so far.  But the code isn't very long yet so I am sure you can figure it out easily.  Of course, if you have any questions, we'll be glad to answer them.

By the way, you've indicated the MIT license in your project, and we are grateful for that, this way code can be ported between our 2 projects without hassle.  But your project is missing a LICENSE file and I would ask you to include it, since simply indicating a license isn't considered sufficient.

Kind regards,
Nando Florestan

**Comment by lostpupil** [comment]
@nandoflorestan Thanks for your remind. I just added the LICENSE file. I am reading your code and try to make some examples later.
